name: CI/CD Innovatech Frontend

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:eks-v1

      - name: Deploy en servidor K3s
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            podman pull ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:eks-v1
            podman tag ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:eks-v1 localhost:5000/innovatech-frontend:eks-v1
            podman push --tls-verify=false localhost:5000/innovatech-frontend:eks-v1
            kubectl rollout restart deployment/innovatech-frontend -n user2
            kubectl rollout status deployment/innovatech-frontend -n user2
